In [1]:
import os
import site
import sys

import numpy as np
import pandas as pd
from IPython.display import display
from matplotlib import pyplot as plt

sys.path.append("../source")
%matplotlib inline

In [2]:
pd.set_option("expand_frame_repr", True)
pd.set_option("colheader_justify", "right")
pd.set_option("precision", 4)

pd.set_option("max_rows", 100)
pd.set_option("display.width", 200)
pd.set_option("max_columns", 100)
pd.set_option("max_colwidth", 50)
pd.set_option("column_space", 40)

In [3]:
np.set_printoptions(precision=6)
np.set_printoptions(suppress=True)

.format(
    year=year,
    lat=lat,
    lon=lon,
    leap=leap_year,
    interval=interval,
    utc=utc,
    name=your_name,
    email=your_email,
    mailing_list=mailing_list,
    affiliation=your_affiliation,
    reason=reason_for_use,
    api=api_key,
    attr=attributes,
)

attributes = [
    "Source",
    "Location ID",
    "City",
    "State",
    "Country",
    "Latitude",
    "Longitude",
    "Time Zone",
    "Elevation",
    "Local Time Zone",
    "Clearsky DHI Units",
    "Clearsky DNI Units",
    "Clearsky GHI Units",
    "Dew Point Units",
    "DHI Units",
    "DNI Units",
    "GHI Units",
    "Solar Zenith Angle Units",
    "Temperature Units",
    "Pressure Units",
    "Relative Humidity Units",
    "Precipitable Water Units",
    "Wind Direction Units",
    "Wind Speed",
    "Cloud Type -15",
    "Cloud Type 0",
    "Cloud Type 1",
    "Cloud Type 2",
    "Cloud Type 3",
    "Cloud Type 4",
    "Cloud Type 5",
    "Cloud Type 6",
    "Cloud Type 7",
    "Cloud Type 8",
    "Cloud Type 9",
    "Cloud Type 10",
    "Cloud Type 11",
    "Cloud Type 12",
    "Fill Flag 0",
    "Fill Flag 1",
    "Fill Flag 2",
    "Fill Flag 3",
    "Fill Flag 4",
    "Fill Flag 5",
    "Surface Albedo Units",
    "Version",
]

In [62]:
attributes = [
    "Source",
    "Location ID",
    "City",
    "State",
    "Country",
    "Latitude",
    "Longitude",
    "Time Zone",
    "Elevation",
    "Local Time Zone",
    "DHI",
    "DNI",
    "GHI",
    "Dew Points",
    "DHI Units",
    "DNI Units",
    "GHI Units",
    "Solar Zenith Angle Units",
    "Temperature Units",
    "Pressure Units",
    "Relative Humidity Units",
    "Precipitable Water Units",
    "Wind Direction Units",
    "Wind Speed",
    "Cloud Type -15",
    "Cloud Type 0",
    "Cloud Type 1",
    "Cloud Type 2",
    "Cloud Type 3",
    "Cloud Type 4",
    "Cloud Type 5",
    "Cloud Type 6",
    "Cloud Type 7",
    "Cloud Type 8",
    "Cloud Type 9",
    "Cloud Type 10",
    "Cloud Type 11",
    "Cloud Type 12",
    "Fill Flag 0",
    "Fill Flag 1",
    "Fill Flag 2",
    "Fill Flag 3",
    "Fill Flag 4",
    "Fill Flag 5",
    "Surface Albedo Units",
    "Version",
]
# attributes = [x.replace(" ", "_").lower() for x in attributes]
# attrs = ','.join(attributes)

In [4]:
attributes = "air_temperature, clearsky_dhi, clearsky_dni, clearsky_ghi, cloud_type, dew_point, dhi, dni, fill_flag, ghi, ghuv-280-400, ghuv-285-385, relative_humidity, solar_zenith_angle, surface_albedo, surface_pressure, total_precipitable_water, wind_direction, wind_speed"

attrs = attributes.replace(" ", "")
# attrs = attrs.split(",")# .strip()

# Set the attributes to extract (e.g., dhi, ghi, etc.), separated by commas.
# attrs = "ghi,dhi,dni,wind_speed,air_temperature,solar_zenith_angle"
attrs = ""
print(attrs)

In [5]:
# Declare all variables as strings. Spaces must be replaced with '+', i.e., change 'John Smith' to 'John+Smith'.

# Define the lat, long of the location and the year
lat, lon, year = 36.000, -96.000, 2010

# You must request an NSRDB api key from the link above
key = "zlLqGig0zfwIx8SJxEDaORdw4OiTv8ByHNqGhdjA"


# Choose year of data
year = "2019"

# Set leap year to true or false. True will return leap day data if present, false will not.
leap_year = "false"

# Set time interval in minutes, i.e., '30' is half hour intervals. Valid intervals are 30 & 60.
interval = "60"

# Specify Coordinated Universal Time (UTC), 'true' will use UTC, 'false' will use the local time zone of the data.
# NOTE: In order to use the NSRDB data in SAM, you must specify UTC as 'false'. SAM requires the data to be in the
# local time zone.
utc = "false"

# Your full name, use '+' instead of spaces.
name = "Gregory+Myers"

# Your reason for using the NSRDB.
use = "UMSI+Capstone+Project"

# Your affiliation
affiliation = "University+of+Michigan"

# Your email address
email = "gamyers@umich.edu"

# Please join our mailing list so we can keep you up-to-date on new developments.
mailing_list = "true"

# Declare url string

# url = f"https://developer.nrel.gov/api/solar/nsrdb_psm3_download.csv?wkt=POINT({lon}%20{lat})&names={year}\
# &leap_day={leap_year}&interval={interval}&utc={utc}&full_name={name}&email={email}&affiliation={affiliation}\
# &mailing_list={mailing_list}&reason={use}&api_key={key}&attributes={attrs}"

url = f"https://developer.nrel.gov/api/solar/nsrdb_psm3_download.csv?wkt=POINT({lon}%20{lat})&names={year}\
&leap_day={leap_year}&interval={interval}&utc={utc}&full_name={name}&email={email}&affiliation={affiliation}\
&mailing_list={mailing_list}&reason={use}&api_key={key}&attributes={attrs}"

In [6]:
print(url)

https://developer.nrel.gov/api/solar/nsrdb_psm3_download.csv?wkt=POINT(-96.0%2036.0)&names=2019&leap_day=false&interval=60&utc=false&full_name=Gregory+Myers&email=gamyers@umich.edu&affiliation=University+of+Michigan&mailing_list=true&reason=UMSI+Capstone+Project&api_key=zlLqGig0zfwIx8SJxEDaORdw4OiTv8ByHNqGhdjA&attributes=

In [53]:
dft = pd.read_csv(url, nrows=1e5)

In [54]:
display(dft)

,Source,Location ID,City,State,Country,Latitude,Longitude,Time Zone,Elevation,Local Time Zone,Clearsky DHI Units,Clearsky DNI Units,Clearsky GHI Units,Dew Point Units,DHI Units,DNI Units,GHI Units,Solar Zenith Angle Units,Temperature Units,Pressure Units,Relative Humidity Units,Precipitable Water Units,Wind Direction Units,Wind Speed,Cloud Type -15,Cloud Type 0,Cloud Type 1,Cloud Type 2,Cloud Type 3,Cloud Type 4,Cloud Type 5,Cloud Type 6,Cloud Type 7,Cloud Type 8,Cloud Type 9,Cloud Type 10,Cloud Type 11,Cloud Type 12,Fill Flag 0,Fill Flag 1,Fill Flag 2,Fill Flag 3,Fill Flag 4,Fill Flag 5,Surface Albedo Units,Version
0,NSRDB,720015,-,-,-,36.01,-96.02,-6,201,-6,w/m2,w/m2,w/m2,c,w/m2,w/m2,w/m2,Degree,c,mbar,%,cm,Degrees,m/s,NaN,Clear,Probably Clear,Fog,Water,Super-Cooled Water,Mixed,Opaque Ice,Cirrus,Overlapping,Overshooting,Unknown,Dust,Smoke,NaN,Missing Image,Low Irradiance,Exceeds Clearsky,Missing CLoud Properties,Rayleigh Violation,NaN,3.1.1
1,Year,Month,Day,Hour,Minute,Temperature,Clearsky DHI,Clearsky DNI,Clearsky GHI,Cloud Type,Dew Point,DHI,DNI,Fill Flag,GHI,Relative Humidity,Solar Zenith Angle,Surface Albedo,Pressure,Precipitable Water,Wind Direction,Wind Speed,Global Horizontal UV Irradiance (280-400nm),Global Horizontal UV Irradiance (295-385nm),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2019,1,1,0,30,-3.9000000000000004,0,0,0,0,-6.1000000000000005,0,0,0,0,84.62,167.01,0.18,1000,0.8,347,5.1000000000000005,0.0000,0.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2019,1,1,1,30,-4.5,0,0,0,0,-7,0,0,0,0,82.55,161.23,0.18,1001,0.7000000000000001,349,4.800000000000001,0.0000,0.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2019,1,1,2,30,-5.1000000000000005,0,0,0,0,-7.800000000000001,0,0,0,0,81.45,150.51,0.18,1001,0.7000000000000001,352,4.4,0.0000,0.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8757,2019,12,31,19,30,2.9000000000000004,0,0,0,4,1.8,0,0,0,0,92.32000000000001,115.55,0.18,994,0.9,342,6.1000000000000005,0.0000,0.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8758,2019,12,31,20,30,1.1,0,0,0,4,-0.1,0,0,0,0,91.42,127.58,0.18,995,0.8,342,6.4,0.0000,0.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8759,2019,12,31,21,30,-0.6000000000000001,0,0,0,4,-2,0,0,0,0,90.24,139.69,0.18,996,0.8,343,6,0.0000,0.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8760,2019,12,31,22,30,-2,0,0,0,4,-3.6,0,0,0,0,89.04,151.52,0.18,998,0.8,344,5.7,0.0000,0.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8761,2019,12,31,23,30,-3.1,0,0,0,0,-5,0,0,0,0,86.84,162.04,0.18,999,0.8,345,5.4,0.0000,0.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [55]:
dfm = dft.iloc[:1].copy()
dfm

,Source,Location ID,City,State,Country,Latitude,Longitude,Time Zone,Elevation,Local Time Zone,Clearsky DHI Units,Clearsky DNI Units,Clearsky GHI Units,Dew Point Units,DHI Units,DNI Units,GHI Units,Solar Zenith Angle Units,Temperature Units,Pressure Units,Relative Humidity Units,Precipitable Water Units,Wind Direction Units,Wind Speed,Cloud Type -15,Cloud Type 0,Cloud Type 1,Cloud Type 2,Cloud Type 3,Cloud Type 4,Cloud Type 5,Cloud Type 6,Cloud Type 7,Cloud Type 8,Cloud Type 9,Cloud Type 10,Cloud Type 11,Cloud Type 12,Fill Flag 0,Fill Flag 1,Fill Flag 2,Fill Flag 3,Fill Flag 4,Fill Flag 5,Surface Albedo Units,Version
0,NSRDB,720015,-,-,-,36.01,-96.02,-6,201,-6,w/m2,w/m2,w/m2,c,w/m2,w/m2,w/m2,Degree,c,mbar,%,cm,Degrees,m/s,NaN,Clear,Probably Clear,Fog,Water,Super-Cooled Water,Mixed,Opaque Ice,Cirrus,Overlapping,Overshooting,Unknown,Dust,Smoke,NaN,Missing Image,Low Irradiance,Exceeds Clearsky,Missing CLoud Properties,Rayleigh Violation,NaN,3.1.1

header = (
    [
        "Year",
        "Month",
        "Day",
        "Hour",
        "Minute",
        "Temperature",
        "Clearsky DHI",
        "Clearsky DNI",
        "Clearsky GHI",
        "Cloud Type",
        "Dew Point",
        "DHI",
        "DNI",
        "Fill Flag",
        "GHI",
        "Relative Humidity",
        "Solar Zenith Angle",
        "Surface Albedo",
        "Pressure",
        "Precipitable Water",
        "Wind Direction",
        "Wind Speed",
        "Global Horizontal UV Irradiance (280-400nm)",
        "Global Horizontal UV Irradiance (295-385nm)",
    ],
)

In [78]:
header = dft.iloc[1].tolist()
print(header)
header = [item.replace(" ", "_") if isinstance(item, str) else item for item in header]
print(header)

dfh = dft.iloc[1:].copy()
dfh.columns=header
dfh.drop(1, axis=0, inplace=True)
dfh = dfh.loc[:, dfh.columns.notnull()].copy()
dfh.reset_index(drop=True, inplace=True)

['Year', 'Month', 'Day', 'Hour', 'Minute', 'Temperature', 'Clearsky DHI', 'Clearsky DNI', 'Clearsky GHI', 'Cloud Type', 'Dew Point', 'DHI', 'DNI', 'Fill Flag', 'GHI', 'Relative Humidity', 'Solar Zenith Angle', 'Surface Albedo', 'Pressure', 'Precipitable Water', 'Wind Direction', 'Wind Speed', 'Global Horizontal UV Irradiance (280-400nm)', 'Global Horizontal UV Irradiance (295-385nm)', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
['Year', 'Month', 'Day', 'Hour', 'Minute', 'Temperature', 'Clearsky_DHI', 'Clearsky_DNI', 'Clearsky_GHI', 'Cloud_Type', 'Dew_Point', 'DHI', 'DNI', 'Fill_Flag', 'GHI', 'Relative_Humidity', 'Solar_Zenith_Angle', 'Surface_Albedo', 'Pressure', 'Precipitable_Water', 'Wind_Direction', 'Wind_Speed', 'Global_Horizontal_UV_Irradiance_(280-400nm)', 'Global_Horizontal_UV_Irradiance_(295-385nm)', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]

In [79]:
display(dfh)

,Year,Month,Day,Hour,Minute,Temperature,Clearsky_DHI,Clearsky_DNI,Clearsky_GHI,Cloud_Type,Dew_Point,DHI,DNI,Fill_Flag,GHI,Relative_Humidity,Solar_Zenith_Angle,Surface_Albedo,Pressure,Precipitable_Water,Wind_Direction,Wind_Speed,Global_Horizontal_UV_Irradiance_(280-400nm),Global_Horizontal_UV_Irradiance_(295-385nm)
0,2019,1,1,0,30,-3.9000000000000004,0,0,0,0,-6.1000000000000005,0,0,0,0,84.62,167.01,0.18,1000,0.8,347,5.1000000000000005,0.0000,0.0000
1,2019,1,1,1,30,-4.5,0,0,0,0,-7,0,0,0,0,82.55,161.23,0.18,1001,0.7000000000000001,349,4.800000000000001,0.0000,0.0000
2,2019,1,1,2,30,-5.1000000000000005,0,0,0,0,-7.800000000000001,0,0,0,0,81.45,150.51,0.18,1001,0.7000000000000001,352,4.4,0.0000,0.0000
3,2019,1,1,3,30,-5.5,0,0,0,0,-8.3,0,0,0,0,80.42,138.62,0.18,1002,0.7000000000000001,353,4.1000000000000005,0.0000,0.0000
4,2019,1,1,4,30,-5.7,0,0,0,4,-8.700000000000001,0,0,0,0,79.26,126.5,0.18,1002,0.7000000000000001,354,4,0.0000,0.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2019,12,31,19,30,2.9000000000000004,0,0,0,4,1.8,0,0,0,0,92.32000000000001,115.55,0.18,994,0.9,342,6.1000000000000005,0.0000,0.0000
8756,2019,12,31,20,30,1.1,0,0,0,4,-0.1,0,0,0,0,91.42,127.58,0.18,995,0.8,342,6.4,0.0000,0.0000
8757,2019,12,31,21,30,-0.6000000000000001,0,0,0,4,-2,0,0,0,0,90.24,139.69,0.18,996,0.8,343,6,0.0000,0.0000
8758,2019,12,31,22,30,-2,0,0,0,4,-3.6,0,0,0,0,89.04,151.52,0.18,998,0.8,344,5.7,0.0000,0.0000
8759,2019,12,31,23,30,-3.1,0,0,0,0,-5,0,0,0,0,86.84,162.04,0.18,999,0.8,345,5.4,0.0000,0.0000

In [7]:
skiprows = 2
nrows = 24
df = pd.read_csv(url, skiprows=skiprows, nrows=nrows)

In [19]:
df.columns

Index(['Year', 'Month', 'Day', 'Hour', 'Minute', 'Temperature', 'Clearsky DHI', 'Clearsky DNI', 'Clearsky GHI', 'Cloud Type', 'Dew Point', 'DHI', 'DNI', 'Fill Flag', 'GHI', 'Relative Humidity',
       'Solar Zenith Angle', 'Surface Albedo', 'Pressure', 'Precipitable Water', 'Wind Direction', 'Wind Speed', 'Global Horizontal UV Irradiance (280-400nm)',
       'Global Horizontal UV Irradiance (295-385nm)'],
      dtype='object')

In [102]:
df.columns

Index(['Year', 'Month', 'Day', 'Hour', 'Minute', 'Temperature', 'Clearsky DHI', 'Clearsky DNI', 'Clearsky GHI', 'Cloud Type', 'Dew Point', 'DHI', 'DNI', 'Fill Flag', 'GHI', 'Relative Humidity',
       'Solar Zenith Angle', 'Surface Albedo', 'Pressure', 'Precipitable Water', 'Wind Direction', 'Wind Speed', 'Global Horizontal UV Irradiance (280-400nm)',
       'Global Horizontal UV Irradiance (295-385nm)'],
      dtype='object')

# Return just the first 2 lines to get metadata:
info = pd.read_csv(url, nrows=5)

# See metadata for specified properties, e.g., timezone and elevation
timezone, elevation = info["Local Time Zone"], info["Elevation"]

# View metadata
info

# Return all but first 2 lines of csv to get data:
df = pd.read_csv(
    "http://developer.nrel.gov/api/solar/nsrdb_psm3_download.csv?wkt=POINT({lon}%20{lat})&names={year}&leap_day={leap}&interval={interval}&utc={utc}&full_name={name}&email={email}&affiliation={affiliation}&mailing_list={mailing_list}&reason={reason}&api_key={api}&attributes={attr}".format(
        year=year,
        lat=lat,
        lon=lon,
        leap=leap_year,
        interval=interval,
        utc=utc,
        name=your_name,
        email=your_email,
        mailing_list=mailing_list,
        affiliation=your_affiliation,
        reason=reason_for_use,
        api=api_key,
        attr=attributes,
    ),
    skiprows=2,
)

In [86]:
# Set the time index in the pandas dataframe:
df = df.set_index(
    pd.date_range("1/1/{yr}".format(yr=year), freq=interval + "Min", periods=525600 / int(interval))
)

# take a look
print(df.shape)
df.head()

(8760, 24)

,Year,Month,Day,Hour,Minute,Temperature,Clearsky DHI,Clearsky DNI,Clearsky GHI,Cloud Type,Dew Point,DHI,DNI,Fill Flag,GHI,Relative Humidity,Solar Zenith Angle,Surface Albedo,Pressure,Precipitable Water,Wind Direction,Wind Speed,Global Horizontal UV Irradiance (280-400nm),Global Horizontal UV Irradiance (295-385nm)
2019-01-01 00:00:00,2019,1,1,0,30,-3.9,0,0,0,0,-6.1,0,0,0,0,84.62,167.01,0.18,1000,0.8,347,5.1,0.0,0.0
2019-01-01 01:00:00,2019,1,1,1,30,-4.5,0,0,0,0,-7.0,0,0,0,0,82.55,161.23,0.18,1001,0.7,349,4.8,0.0,0.0
2019-01-01 02:00:00,2019,1,1,2,30,-5.1,0,0,0,0,-7.8,0,0,0,0,81.45,150.51,0.18,1001,0.7,352,4.4,0.0,0.0
2019-01-01 03:00:00,2019,1,1,3,30,-5.5,0,0,0,0,-8.3,0,0,0,0,80.42,138.62,0.18,1002,0.7,353,4.1,0.0,0.0
2019-01-01 04:00:00,2019,1,1,4,30,-5.7,0,0,0,4,-8.7,0,0,0,0,79.26,126.50,0.18,1002,0.7,354,4.0,0.0,0.0

In [87]:
df[(df["Month"] == 1) & (df["Hour"] >= 6) & (df["Hour"] <= 18)]

,Year,Month,Day,Hour,Minute,Temperature,Clearsky DHI,Clearsky DNI,Clearsky GHI,Cloud Type,Dew Point,DHI,DNI,Fill Flag,GHI,Relative Humidity,Solar Zenith Angle,Surface Albedo,Pressure,Precipitable Water,Wind Direction,Wind Speed,Global Horizontal UV Irradiance (280-400nm),Global Horizontal UV Irradiance (295-385nm)
2019-01-01 06:00:00,2019,1,1,6,30,-5.9,0,0,0,4,-9.2,0,0,0,0,77.48,102.80,0.18,1003,0.7,359,3.6,0.0000,0.0000
2019-01-01 07:00:00,2019,1,1,7,30,-5.3,3,24,2,4,-9.3,0,8,14,0,73.44,91.67,0.18,1004,0.7,180,3.8,0.0000,0.0000
2019-01-01 08:00:00,2019,1,1,8,30,-4.1,43,542,125,4,-9.2,18,0,100,18,67.64,81.28,0.18,1005,0.7,4,4.3,0.0000,0.0000
2019-01-01 09:00:00,2019,1,1,9,30,-2.9,63,757,293,4,-9.0,47,0,21,47,62.99,72.33,0.18,1006,0.7,5,4.3,2.3552,1.8180
2019-01-01 10:00:00,2019,1,1,10,30,-1.9,75,851,432,4,-8.4,117,8,18,120,61.07,65.17,0.18,1005,0.7,182,3.8,6.3925,4.9751
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-01-31 14:00:00,2019,1,31,14,30,5.5,98,820,514,4,4.1,179,30,4,194,90.99,59.53,0.17,993,1.3,176,2.5,10.7246,8.3785
2019-01-31 15:00:00,2019,1,31,15,30,4.8,90,726,373,4,4.1,65,0,0,65,95.51,67.05,0.17,993,1.3,177,2.2,3.4124,2.6512
2019-01-31 16:00:00,2019,1,31,16,30,4.1,71,534,196,4,4.1,19,0,86,19,100.00,76.43,0.17,993,1.3,176,2.2,0.9183,0.7039
2019-01-31 17:00:00,2019,1,31,17,30,3.8,26,137,33,4,3.8,4,0,86,4,100.00,86.90,0.17,993,1.3,175,2.2,0.0000,0.0000
2019-01-31 18:00:00,2019,1,31,18,30,3.3,0,0,0,4,3.3,0,0,0,0,100.00,98.56,0.18,994,1.3,171,1.8,0.0000,0.0000

In [88]:
df[:24]

,Year,Month,Day,Hour,Minute,Temperature,Clearsky DHI,Clearsky DNI,Clearsky GHI,Cloud Type,Dew Point,DHI,DNI,Fill Flag,GHI,Relative Humidity,Solar Zenith Angle,Surface Albedo,Pressure,Precipitable Water,Wind Direction,Wind Speed,Global Horizontal UV Irradiance (280-400nm),Global Horizontal UV Irradiance (295-385nm)
2019-01-01 00:00:00,2019,1,1,0,30,-3.9,0,0,0,0,-6.1,0,0,0,0,84.62,167.01,0.18,1000,0.8,347,5.1,0.0000,0.0000
2019-01-01 01:00:00,2019,1,1,1,30,-4.5,0,0,0,0,-7.0,0,0,0,0,82.55,161.23,0.18,1001,0.7,349,4.8,0.0000,0.0000
2019-01-01 02:00:00,2019,1,1,2,30,-5.1,0,0,0,0,-7.8,0,0,0,0,81.45,150.51,0.18,1001,0.7,352,4.4,0.0000,0.0000
2019-01-01 03:00:00,2019,1,1,3,30,-5.5,0,0,0,0,-8.3,0,0,0,0,80.42,138.62,0.18,1002,0.7,353,4.1,0.0000,0.0000
2019-01-01 04:00:00,2019,1,1,4,30,-5.7,0,0,0,4,-8.7,0,0,0,0,79.26,126.50,0.18,1002,0.7,354,4.0,0.0000,0.0000
2019-01-01 05:00:00,2019,1,1,5,30,-5.9,0,0,0,4,-9.0,0,0,0,0,78.79,114.49,0.18,1003,0.7,356,3.9,0.0000,0.0000
2019-01-01 06:00:00,2019,1,1,6,30,-5.9,0,0,0,4,-9.2,0,0,0,0,77.48,102.80,0.18,1003,0.7,359,3.6,0.0000,0.0000
2019-01-01 07:00:00,2019,1,1,7,30,-5.3,3,24,2,4,-9.3,0,8,14,0,73.44,91.67,0.18,1004,0.7,180,3.8,0.0000,0.0000
2019-01-01 08:00:00,2019,1,1,8,30,-4.1,43,542,125,4,-9.2,18,0,100,18,67.64,81.28,0.18,1005,0.7,4,4.3,0.0000,0.0000
2019-01-01 09:00:00,2019,1,1,9,30,-2.9,63,757,293,4,-9.0,47,0,21,47,62.99,72.33,0.18,1006,0.7,5,4.3,2.3552,1.8180
2019-01-01 10:00:00,2019,1,1,10,30,-1.9,75,851,432,4,-8.4,117,8,18,120,61.07,65.17,0.18,1005,0.7,182,3.8,6.3925,4.9751
2019-01-01 11:00:00,2019,1,1,11,30,-1.0,81,893,521,4,-7.6,124,0,0,124,60.80,60.50,0.18,1005,0.7,354,3.4,6.8160,5.3220
2019-01-01 12:00:00,2019,1,1,12,30,-0.5,84,904,550,4,-6.9,126,0,0,126,61.87,58.95,0.18,1004,0.7,347,3.3,6.9884,5.4613
2019-01-01 13:00:00,2019,1,1,13,30,-0.3,82,889,516,4,-6.5,108,0,0,108,63.15,60.76,0.18,1003,0.7,347,3.2,5.9272,4.6273
2019-01-01 14:00:00,2019,1,1,14,30,-0.5,75,838,421,4,-6.2,129,25,0,139,65.35,65.64,0.18,1003,0.8,350,3.2,7.3785,5.7401
2019-01-01 15:00:00,2019,1,1,15,30,-1.2,64,732,278,7,-6.2,68,0,14,68,68.82,72.97,0.18,1003,0.8,355,3.0,3.3873,2.6121
2019-01-01 16:00:00,2019,1,1,16,30,-2.6,42,496,111,4,-6.3,21,0,100,21,75.53,82.03,0.18,1003,0.8,180,2.3,0.0000,0.0000
2019-01-01 17:00:00,2019,1,1,17,30,-3.6,0,0,0,7,-6.4,0,0,0,0,80.95,92.51,0.18,1003,0.8,3,1.7,0.0000,0.0000
2019-01-01 18:00:00,2019,1,1,18,30,-4.3,0,0,0,7,-6.6,0,0,0,0,84.05,103.69,0.18,1004,0.8,182,1.6,0.0000,0.0000
2019-01-01 19:00:00,2019,1,1,19,30,-4.3,0,0,0,7,-6.6,0,0,0,0,84.09,115.41,0.18,1004,0.9,357,1.8,0.0000,0.0000
2019-01-01 20:00:00,2019,1,1,20,30,-4.3,0,0,0,7,-6.8,0,0,0,0,82.97,127.44,0.18,1004,0.9,356,1.9,0.0000,0.0000
2019-01-01 21:00:00,2019,1,1,21,30,-4.3,0,0,0,7,-7.0,0,0,0,0,81.39,139.56,0.18,1004,0.9,354,1.9,0.0000,0.0000
2019-01-01 22:00:00,2019,1,1,22,30,-4.3,0,0,0,6,-7.1,0,0,0,0,80.58,151.39,0.18,1004,1.0,349,1.9,0.0000,0.0000
2019-01-01 23:00:00,2019,1,1,23,30,-4.2,0,0,0,6,-7.2,0,0,0,0,79.48,161.90,0.18,1003,1.0,340,1.7,0.0000,0.0000

In [89]:
df.to_csv(
    "../data/test_download_2019.csv",
    index=True,
)

In [92]:
# Print column names
df.columns

Index(['Year', 'Month', 'Day', 'Hour', 'Minute', 'Temperature', 'Clearsky DHI', 'Clearsky DNI', 'Clearsky GHI', 'Cloud Type', 'Dew Point', 'DHI', 'DNI', 'Fill Flag', 'GHI', 'Relative Humidity',
       'Solar Zenith Angle', 'Surface Albedo', 'Pressure', 'Precipitable Water', 'Wind Direction', 'Wind Speed', 'Global Horizontal UV Irradiance (280-400nm)',
       'Global Horizontal UV Irradiance (295-385nm)'],
      dtype='object')

In [ ]:
# import additional module for SAM simulation:
# import site

# Use site.addsitedir() to set the path to the SAM SDK API. Set path to the python directory.
site.addsitedir("/Applications/sam-sdk-2015-6-30-r3/languages/python/")
import sscapi

ssc = sscapi.PySSC()

# Resource inputs for SAM model:
wfd = ssc.data_create()
ssc.data_set_number(wfd, "lat", lat)
ssc.data_set_number(wfd, "lon", lon)
ssc.data_set_number(wfd, "tz", timezone)
ssc.data_set_number(wfd, "elev", elevation)
ssc.data_set_array(wfd, "year", df.index.year)
ssc.data_set_array(wfd, "month", df.index.month)
ssc.data_set_array(wfd, "day", df.index.day)
ssc.data_set_array(wfd, "hour", df.index.hour)
ssc.data_set_array(wfd, "minute", df.index.minute)
ssc.data_set_array(wfd, "dn", df["DNI"])
ssc.data_set_array(wfd, "df", df["DHI"])
ssc.data_set_array(wfd, "wspd", df["Wind Speed"])
ssc.data_set_array(wfd, "tdry", df["Temperature"])

# Create SAM compliant object
dat = ssc.data_create()
ssc.data_set_table(dat, "solar_resource_data", wfd)
ssc.data_free(wfd)

# Specify the system Configuration
# Set system capacity in MW
system_capacity = 4
ssc.data_set_number(dat, "system_capacity", system_capacity)

# Set DC/AC ratio (or power ratio). See https://sam.nrel.gov/sites/default/files/content/virtual_conf_july_2013/07-sam-virtual-conference-2013-woodcock.pdf
ssc.data_set_number(dat, "dc_ac_ratio", 1.1)

# Set tilt of system in degrees
ssc.data_set_number(dat, "tilt", 25)

# Set azimuth angle (in degrees) from north (0 degrees)
ssc.data_set_number(dat, "azimuth", 180)

# Set the inverter efficency
ssc.data_set_number(dat, "inv_eff", 96)

# Set the system losses, in percent
ssc.data_set_number(dat, "losses", 14.0757)

# Specify fixed tilt system (0=Fixed, 1=Fixed Roof, 2=1 Axis Tracker, 3=Backtracted, 4=2 Axis Tracker)
ssc.data_set_number(dat, "array_type", 0)

# Set ground coverage ratio
ssc.data_set_number(dat, "gcr", 0.4)

# Set constant loss adjustment
ssc.data_set_number(dat, "adjust:constant", 0)

# execute and put generation results back into dataframe
mod = ssc.module_create("pvwattsv5")
ssc.module_exec(mod, dat)
df["generation"] = np.array(ssc.data_get_array(dat, "gen"))

# free the memory
ssc.data_free(dat)
ssc.module_free(mod)

In [ ]:
# Divide sum of generation by the number of periods times the system size
df["generation"].sum() / (525600 / int(interval) * system_capacity)

In [ ]:
# Total Energy:
df["generation"].sum()

In [ ]:
plt.style.use("ggplot")


def nsrdb_plot(df, i):
    fig = plt.figure()
    ax = fig.add_subplot(111)
    ax2 = ax.twinx()

    df["90 Degree Zenith"] = 90

    df[["GHI", "DNI", "DHI", "Solar Zenith Angle", "90 Degree Zenith"]][i : i + int(interval)].plot(
        ax=ax,
        figsize=(15, 8),
        yticks=(np.arange(0, 900, 100)),
        style={"90 Degree Zenith": "--", "Solar Zenith Angle": "-o", "DNI": "-o", "DHI": "-o", "GHI": "-o"},
        legend=False,
    )

    df["generation"][i : i + 30].plot(ax=ax2, yticks=(np.arange(0, 4.5, 0.5)), style={"generation": "y-o"})

    ax.grid()
    ax.set_ylabel("W/m2")
    ax2.set_ylabel("kW")
    ax.legend(loc=2, ncol=5, frameon=False)
    ax2.legend(loc=1, frameon=False)

In [ ]:
nsrdb_plot(df, 5050)